### ISSUE TITLE
Add more Mime Types to the default configuration

### ISSUE THREAD

**Issue by rainboyan** [graceframework/grace-framework#686]
```yml
grails:
    mime:
        types:
            all: '*/*'
            css: text/css
            form: application/x-www-form-urlencoded
            js: text/javascript
            multipartForm: multipart/form-data
            txt: text/plain
```
